### ISSUE TITLE
Пыхчи с инстаграма

### ISSUE THREAD

**Issue by machabuntu** [myownhatred/botAPI#1]
Сделай, щобы бот игнорировал результаты из инстаграма при поиске картинок

**Comment by Ubububu** [comment]
net

**Comment by machabuntu** [comment]
> net

da

**Comment by Ubububu** [comment]
> > net
> 
> da

теперь да, ведь надо игнорировать экстремизм

**Comment by myownhatred** [comment]
вытрахал оба ису
